name: phmeter
version: 1.0.5+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  intl: any
  get: 4.6.5
  flutter_switch: ^0.3.2
  window_manager: 0.3.5
  home_widget: 0.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/app_icon/
    - assets/images/
    - icons/
  uses-material-design: true

